### PR TITLE
allow setting useGMT option on subscriptions

### PR DESCRIPTION
**Pull request by jonfreedman**
fixes https://github.com/assylias/jBloomberg/issues/37

### CODE REVIEW

**Comment by jonfreedman** [comment]
I think the Travis build timed out, ran fine on my branch @ https://travis-ci.org/jonfreedman/jBloomberg/builds/424687213

**Comment by assylias** [comment]
@jonfreedman Thank you for this. The times received from a subscription are converted into `OffsetTime` objects at the moment, defaulting to UTC. So if the timestamp of an event is 10am BST (UTC+1), the user receives `10:00Z` instead of `10:00+01:00`. I'd say it's a bug and that we should always use the `useGMT` option. The user can then convert the `OffsetTime` to a suitable time zone if needed.

**Comment by assylias** [comment]
See https://github.com/assylias/jBloomberg/issues/37

**Comment by jonfreedman** [comment]
I believe the issue is that the Bloomberg API claims to respect timezones but it doesn't.  If you run the same code but change your PC timezone, or your terminal settings you'll get different timestamps for the same thing.  This change is to fix that - although according to the documentation all timestamps over B-PIPE are in UTC already.

**Comment by assylias** [comment]
@jonfreedman I've changed the code to always use `useGMT`. The times are stored as `OffsetTime` objects with a UTC offset (i.e. 0). I think that solves the issue.

**Comment by jonfreedman** [comment]
Ah yes, apologies I missed your commit

**Pull request closed without merging**
