### PR TITLE
API Authorization

### PR DESCRIPTION
**Pull request by wjn161**
some api need an authorization, add some code to support this ,see more at [Bloomberg API Developers Guide.pdf](https://github.com/assylias/jBloomberg/files/752002/Bloomberg.API.Developers.Guide.pdf) in Section 7.9

### CODE REVIEW

**Comment by assylias** [comment]
Hi wjn16 - thank you for your PR. I will go through it in the coming days.

**Comment by wjn161** [comment]
Hi,assylias,thanks for your response. some bloomberg server api that i was used need authorization, so i have to add some codes to support it.maybe my implements are not suitable for this project and i think your codes is awesome, so you can go through the developer guide section 7.9 and override them. i'm very glad to use your codes!  thanks very much!

**Comment by assylias** [comment]
Hi @wjn161 - I have had a look at your pull request. It is interesting but the license is not compatible with the Apache license used by the project. Also it would need some tests related to the new code (I've never used the library with SAPI so not sure how it can be done). If I have time in the coming months I will try to add something similar to the project. Thank you anyway for you suggestions.

**Comment by wjn161** [comment]
@assylias okay,I'll close the PR and waiting for your update! :blush:

**Comment by assylias** [comment]
Hi @wjn161 for your information I've merged a PR into the master branch that adds the possibility to use the authorisation API for the Server API and the enterprise products.

**Pull request closed without merging**
